import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { watchLegacyInterface } from '../utils/legacyTranslations';

export type AppLocale = 'en' | 'pt-BR';

const STORAGE_KEY = 'gamepanel.locale';

const ptBR: Record<string, string> = {
  'language.english': 'English',
  'language.portuguese': 'Português (Brasil)',
  'language.label': 'Idioma',
  'nav.gameServers': 'Servidores',
  'nav.hostStatus': 'Status do host',
  'nav.users': 'Administração de usuários',
  'nav.resources': 'Recursos',
  'nav.panelContent': 'Conteúdo do painel',
  'nav.followUs': 'Siga-nos',
  'user.unknown': 'Usuário desconhecido',
  'user.menu': 'Menu do usuário',
  'user.changePassword': 'Alterar senha',
  'user.logout': 'Sair',
  'theme.light': 'Usar tema claro',
  'theme.dark': 'Usar tema escuro',
  'login.username': 'Usuário',
  'login.usernamePlaceholder': 'Digite seu usuário',
  'login.password': 'Senha',
  'login.passwordPlaceholder': 'Digite sua senha',
  'login.signIn': 'Entrar',
  'login.signingIn': 'Entrando…',
  'login.tagline': 'Entre para administrar seus servidores de jogos',
  'login.incorrectTitle': 'Usuário ou senha incorretos',
  'login.incorrectMessage': 'Verifique seus dados de acesso e tente novamente.',
  'login.unable': 'Não foi possível entrar',
  'login.rights': 'Todos os direitos reservados.',
  'login.required': 'Preencha usuário e senha.',
  'login.invalid': 'Não foi possível entrar. Verifique suas credenciais.',
  'settings.title': 'Configurações do servidor',
  'settings.gameConfig': 'Configuração do jogo',
  'settings.config': 'Configuração',
  'settings.files': 'Arquivos',
  'settings.fileManager': 'Gerenciador de arquivos',
  'settings.backups': 'Backups',
  'settings.schedules': 'Agendamentos',
  'settings.scheduledTasks': 'Tarefas agendadas',
  'settings.terminal': 'Terminal',
  'settings.container': 'Contêiner',
  'settings.containerConfig': 'Configuração do contêiner',
  'settings.noAccess': 'Sem acesso a esta seção',
  'settings.noAccessDescription': 'Você não tem permissão para visualizar ou administrar esta parte das configurações.',
  'gameSettings.title': 'Configurações do servidor',
  'gameSettings.search': 'Buscar por nome ou chave…',
  'gameSettings.showing': 'Exibindo {shown} de {total}',
  'gameSettings.noMatch': 'Nenhuma configuração corresponde à busca.',
  'gameSettings.none': 'Nenhuma configuração disponível. Talvez o servidor ainda não tenha sido iniciado.',
  'gameSettings.loading': 'Carregando configurações…',
  'gameSettings.save': 'Salvar',
  'gameSettings.saving': 'Salvando…',
  'gameSettings.noChanges': 'Nenhuma alteração para salvar.',
  'gameSettings.savedRestart': 'Configurações salvas. Reinicie o servidor para aplicar as alterações.',
  'gameSettings.savedNextStart': 'Configurações salvas. Elas serão aplicadas na próxima inicialização.',
  'gameSettings.stopToEdit': 'O servidor deve estar parado para editar estas configurações.',
  'palworld.serverSettings': 'Configurações do servidor',
  'palworld.wipe': 'Limpeza',
  'palworld.adminPassword': 'Senha administrativa',
  'palworld.adminPasswordDescription': 'Usada para ações administrativas no jogo e para a API REST do servidor.',
  'palworld.updateOnStart': 'Atualizar ao iniciar',
  'palworld.updateOnStartDescription': 'Quando ativado, procura e instala atualizações pelo SteamCMD sempre que o servidor inicia.',
  'news.title': 'Notícias',
  'news.hide': 'Ocultar notícias',
  'news.show': 'Mostrar notícias',
  'news.previous': 'Notícia anterior',
  'news.next': 'Próxima notícia',
  'news.pause': 'Pausar',
  'news.resume': 'Continuar',
  'news.none': 'Nenhuma notícia publicada',
  'news.noneDescription': 'As notícias da fonte configurada aparecerão aqui.',
  'host.cpuUsage': 'Uso de CPU',
  'host.ramUsage': 'Uso de RAM',
  'host.diskUsage': 'Uso de disco',
  'host.networkIo': 'Rede E/S',
  'host.cpuHistory': 'Histórico de CPU',
  'host.ramHistory': 'Histórico de RAM',
  'host.diskHistory': 'Histórico de disco',
  'host.networkHistory': 'Histórico de rede',
  'host.incoming': 'Entrada',
  'host.outgoing': 'Saída',
  'servers.none': 'Nenhum servidor de jogo instalado.',
  'servers.noneHint': 'Use “Adicionar servidor” para instalar o primeiro.',
  'servers.add': 'Adicionar servidor',
  'servers.connection': 'Conexão',
  'servers.power': 'Energia',
  'servers.management': 'Gerenciamento',
  'servers.delete': 'Excluir',
  'servers.memory': 'Memória',
  'servers.disk': 'Disco',
  'servers.network': 'Rede',
  'servers.loading': 'Carregando',
  'servers.start': 'Iniciar',
  'servers.stop': 'Parar',
  'servers.restart': 'Reiniciar',
  'servers.serverName': 'Nome do servidor',
  'servers.game': 'Jogo',
  'servers.status': 'Status',
  'servers.metrics': 'Métricas do servidor',
  'servers.customizeMetrics': 'Personalizar métricas visíveis',
  'common.cancel': 'Cancelar',
  'common.delete': 'Excluir',
  'common.optional': 'opcional',
  'common.saving': 'Salvando…',
  'content.title': 'Conteúdo do painel',
  'content.description': 'Publique notícias, links da barra lateral, recursos e tutoriais sem editar arquivos JSON.',
  'content.loading': 'Carregando conteúdo…',
  'content.loadError': 'Não foi possível carregar o conteúdo do painel.',
  'content.save': 'Salvar e publicar',
  'content.saved': 'Conteúdo salvo e publicado.',
  'content.saveError': 'Não foi possível salvar o conteúdo do painel.',
  'content.news': 'Banner de notícias',
  'content.social': 'Links da barra lateral',
  'content.resources': 'Recursos e tutoriais',
  'content.enabled': 'Ativado',
  'content.source': 'Origem do conteúdo',
  'content.rotation': 'Intervalo de rotação (segundos)',
  'content.remoteUrl': 'URL da origem remota',
  'content.sectionTitle': 'Título da seção',
  'content.addNews': 'Adicionar notícia',
  'content.addLink': 'Adicionar link',
  'content.addResource': 'Adicionar recurso',
  'content.itemTitle': 'Título',
  'content.itemDescription': 'Descrição',
  'content.itemType': 'Tipo',
  'content.linkLabel': 'Rótulo',
  'content.url': 'URL',
  'content.icon': 'Ícone',
  'content.category': 'Categoria',
  'content.gameKey': 'Chave do jogo (opcional)',
  'tasks.title': 'Tarefas agendadas',
  'tasks.description': 'Automatize reinicializações, backups e comandos personalizados com agendamento cron',
  'tasks.add': 'Adicionar tarefa',
  'tasks.addFirst': 'Adicione sua primeira tarefa',
  'tasks.none': 'Nenhuma tarefa agendada ainda.',
  'tasks.new': 'Nova tarefa',
  'tasks.edit': 'Editar tarefa',
  'tasks.type': 'Tipo',
  'tasks.schedule': 'Agendamento',
  'tasks.enabled': 'Ativada',
  'tasks.enabledAria': 'Tarefa ativada',
  'tasks.restart': 'Reinicialização',
  'tasks.backup': 'Backup',
  'tasks.custom': 'Comando personalizado',
  'tasks.command': 'Comando',
  'tasks.sleep': 'Aguardar',
  'tasks.seconds': 'segundos',
  'tasks.noSteps': 'Nenhuma etapa.',
  'tasks.preCommands': 'Comandos anteriores',
  'tasks.postCommands': 'Comandos posteriores',
  'tasks.workdir': 'Diretório de trabalho',
  'tasks.includeArtifact': 'Incluir artefato do servidor',
  'tasks.includeArtifactDescription': 'Inclui no backup o arquivo baixável do servidor Minecraft',
  'tasks.save': 'Salvar tarefa',
  'tasks.loadError': 'Não foi possível carregar as tarefas agendadas',
  'tasks.saveError': 'Não foi possível salvar a tarefa',
  'tasks.deleteError': 'Não foi possível excluir a tarefa',
  'tasks.scheduleRequired': 'O agendamento é obrigatório.',
  'tasks.commandRequired': 'O comando é obrigatório.',
  'tasks.deleteTitle': 'Excluir tarefa',
  'tasks.deleteMessage': 'Excluir esta tarefa agendada do tipo “{type}”? Esta ação não pode ser desfeita.',
  'tasks.neverRun': 'Nunca executada',
  'tasks.success': 'Sucesso',
  'tasks.failed': 'Falhou',
  'tasks.skipped': 'Ignorada',
  'tasks.running': 'Em execução',
  'tasks.next': 'Próxima',
  'tasks.last': 'Última',
  'tasks.everyMinutes': 'A cada {count} minuto(s)',
  'tasks.everyHours': 'A cada {count} hora(s)',
  'tasks.everyDayAt': 'Todos os dias às {time}',
  'tasks.everyWeekdayAt': 'Toda(o) {day} às {time}',
  'tasks.day.0': 'domingo',
  'tasks.day.1': 'segunda-feira',
  'tasks.day.2': 'terça-feira',
  'tasks.day.3': 'quarta-feira',
  'tasks.day.4': 'quinta-feira',
  'tasks.day.5': 'sexta-feira',
  'tasks.day.6': 'sábado',
  'tasks.relative.futureMinute': 'em menos de 1 min',
  'tasks.relative.pastMinute': 'há menos de 1 min',
  'tasks.relative.futureMinutes': 'em {count} min',
  'tasks.relative.pastMinutes': 'há {count} min',
  'tasks.relative.futureHours': 'em {count} h',
  'tasks.relative.pastHours': 'há {count} h',
  'tasks.relative.futureDays': 'em {count} d',
  'tasks.relative.pastDays': 'há {count} d',
  'terminal.title': 'Terminal',
  'terminal.serverStopped': 'O servidor precisa estar em execução para abrir o terminal.',
  'terminal.warningTitle': 'Aviso de recurso avançado',
  'terminal.warning': 'Este terminal oferece acesso completo ao shell dentro do contêiner do servidor. O uso incorreto pode danificar o servidor do jogo, excluir arquivos ou expor dados sensíveis. Use com cuidado.',
  'terminal.accept': 'Entendo os riscos, abrir o terminal',
  'terminal.missingServer': 'Identificador do servidor ausente.',
  'terminal.unavailable': 'O acesso ao terminal ficará disponível quando o provisionamento do servidor terminar.',
  'terminal.error': 'Erro no terminal',
  'terminal.connectionError': 'Não foi possível conectar ao terminal.',
  'terminal.sessionError': 'Não foi possível iniciar a sessão do terminal.',
  'backups.title': 'Backups',
  'backups.description': 'Gerencie e baixe os backups de {server}',
  'backups.create': 'Criar backup agora',
  'backups.creating': 'Criando…',
  'backups.unsupported': 'Este servidor não oferece suporte a backups.',
  'backups.unsupportedDescription': 'Este tipo de servidor não oferece suporte a backups.',
  'backups.retention': 'Política de retenção',
  'backups.keepLast': 'Manter os últimos backups',
  'backups.unlimited': 'Ilimitado',
  'backups.count': '{count} backups',
  'backups.keepLastHint': 'Defina como 0 para manter todos os backups.',
  'backups.keepDays': 'Manter backups por quantos dias',
  'backups.days': '{count} dias',
  'backups.forever': 'Para sempre',
  'backups.keepForeverHint': 'Defina como 0 para manter os backups para sempre.',
  'backups.stopBefore': 'Parar o servidor antes do backup',
  'backups.stopBeforeDescription': 'Garante um backup consistente, mas deixa o servidor temporariamente indisponível.',
  'backups.saveRetention': 'Salvar política de retenção',
  'backups.available': 'Backups disponíveis',
  'backups.availableLinux': 'Baixe ou exclua os backups do servidor',
  'backups.availableFull': 'Baixe, restaure ou exclua os backups do servidor',
  'backups.refresh': 'Atualizar',
  'backups.loading': 'Carregando backups…',
  'backups.none': 'Nenhum backup encontrado.',
  'backups.download': 'Baixar',
  'backups.downloading': 'Baixando…',
  'backups.restore': 'Restaurar',
  'backups.restoring': 'Restaurando…',
  'backups.delete': 'Excluir',
  'backups.deleting': 'Excluindo…',
  'container.title': 'Configuração do contêiner',
  'container.description': 'Portas, variáveis de ambiente, volumes e verificação de integridade. Ao salvar, o contêiner Docker será recriado.',
  'container.image': 'Imagem Docker',
  'container.ports': 'Portas',
  'container.volumes': 'Volumes',
  'container.noMounts': 'Nenhum volume configurado.',
  'container.name': 'Nome',
  'container.path': 'Caminho no contêiner',
  'container.addVolume': 'Adicionar volume',
  'container.environment': 'Variáveis de ambiente',
  'container.noVariables': 'Nenhuma variável configurada.',
  'container.addVariable': 'Adicionar variável',
  'container.resourceLimits': 'Limites de recursos',
  'container.resourceLimitsHint': 'Deixe em branco para não limitar. As alterações são aplicadas imediatamente.',
  'container.healthcheck': 'Verificação de integridade',
  'container.healthcheckWarning': 'Uma verificação incorreta pode manter o servidor como indisponível ou impedir que ele conclua a inicialização. Mantenha o padrão da imagem, a menos que conheça a porta ou o processo principal.',
  'container.mode': 'Modo',
  'container.imageDefault': 'Padrão da imagem',
  'container.disabled': 'Desativada',
  'container.override': 'Personalizada',
  'container.type': 'Tipo',
  'container.tcpConnect': 'Conexão TCP',
  'container.process': 'Processo',
  'container.command': 'Comando',
  'container.port': 'Porta',
  'container.processName': 'Nome do processo',
  'container.commandArgs': 'Comando (argumentos separados por espaço)',
  'container.interval': 'Intervalo (s)',
  'container.timeout': 'Tempo limite (s)',
  'container.startPeriod': 'Período inicial (s)',
  'container.retries': 'Tentativas',
  'container.saved': 'Configuração salva. O contêiner será recriado.',
  'container.save': 'Salvar configuração do contêiner',
  'container.loadError': 'Não foi possível carregar a configuração do servidor',
  'container.saveError': 'Não foi possível salvar a configuração',
  'container.restartRequired': 'Reinicialização necessária',
  'container.restartDescription': 'Salvar a configuração do contêiner reiniciará o servidor imediatamente. Qualquer sessão de jogo em andamento será interrompida.',
  'container.warnPlayers': 'Avise os jogadores antes de continuar.',
  'container.confirmRestart': 'Confirmar e reiniciar',
  'files.root': 'Raiz',
  'files.refresh': 'Atualizar',
  'files.hideHidden': 'Ocultar arquivos ocultos',
  'files.showHidden': 'Mostrar arquivos ocultos',
  'files.newFolder': 'Nova pasta',
  'files.newFile': 'Novo arquivo',
  'files.upload': 'Enviar arquivos',
  'files.copied': 'Copiado!',
  'files.copyPath': 'Copiar caminho',
  'files.dropUpload': 'Solte os arquivos para enviar',
  'files.loading': 'Carregando arquivos…',
  'files.extract': 'Extrair arquivo',
  'files.download': 'Baixar',
  'files.rename': 'Renomear',
  'files.delete': 'Excluir',
  'files.dragUpload': 'Arraste e solte arquivos aqui para enviar',
  'files.failed': 'Falhou',
  'files.copy': 'Copiar',
  'files.save': 'Salvar',
  'files.close': 'Fechar',
  'files.loadingFile': 'Carregando arquivo…',
  'files.loadingEditor': 'Carregando editor…',
  'wipe.title': 'Limpeza',
  'wipe.soft': 'Limpeza parcial',
  'wipe.hard': 'Limpeza completa',
  'wipe.deleted': 'Excluído',
  'wipe.kept': 'Mantido',
  'wipe.serverRunning': 'O servidor deve estar parado para realizar a limpeza. Depois disso, ele continuará parado e gerará um mundo novo na próxima inicialização.',
  'wipe.complete': '{mode} concluída.',
  'wipe.completePaths': '{mode} concluída ({count} caminho(s) removido(s)).',
  'wipe.startFresh': 'O servidor está parado — inicie-o quando quiser gerar um mundo novo.',
  'wipe.soft.description': 'Redefine o mundo e o progresso dos jogadores, mantendo a configuração do servidor. Um mundo novo será gerado na próxima inicialização.',
  'wipe.soft.confirm': 'Isso redefine o mundo e o progresso dos jogadores. Configuração, lista de permissões e mods serão mantidos. Não há backup automático e a ação não pode ser desfeita.',
  'wipe.hard.description': 'Reinstalação completa: apaga todos os volumes persistentes e reinstala o jogo mantendo a configuração do servidor. O servidor será reinstalado e iniciado automaticamente.',
  'wipe.hard.confirm': 'Isso apaga TODOS os volumes persistentes — mundo, personagens, mods, arquivos de configuração e backups — e reinstala o jogo do zero. Nada será preservado e a ação não pode ser desfeita.',
  'wipe.item.worldPlayers': 'Mundo salvo e dados dos jogadores',
  'wipe.item.worldsPlayers': 'Mundos e dados dos jogadores',
  'wipe.item.universe': 'Universo (mundos e jogadores)',
  'wipe.item.everything': 'Tudo no disco: mundo, personagens, mods e arquivos de configuração',
  'wipe.item.allBackups': 'Todos os backups',
  'wipe.item.serverConfig': 'Configuração do servidor',
  'wipe.item.serverSettings': 'Configuração do servidor (ajustes)',
  'wipe.item.whitelistBans': 'Lista de permissões e banimentos',
  'wipe.item.pluginsMods': 'Plugins e mods',
  'wipe.item.mods': 'Mods',
  'wipe.item.backups': 'Backups',
  'users.title': 'Usuários',
  'users.create': 'Criar usuário',
  'users.creating': 'Criando…',
  'users.edit': 'Editar',
  'users.none': 'Nenhum usuário encontrado.',
  'users.max': 'Máximo de {count}',
  'users.limit': 'Limite de usuários atingido (máximo de {count}).',
  'users.superAdmin': 'Superadministrador',
  'users.enabled': 'Conta ativada',
  'users.disabled': 'Conta desativada',
  'users.deleteAria': 'Excluir usuário {username}',
  'users.createDescription': 'Crie a conta diretamente pelo painel. O usuário será ativado imediatamente.',
  'users.limitDescription': 'Limite atingido: máximo de {count} usuários.',
  'users.username': 'Nome de usuário',
  'users.password': 'Senha',
  'users.confirmPassword': 'Confirmar senha',
  'users.close': 'Fechar',
  'users.noSelection': 'Nenhum usuário selecionado.',
  'users.rootLocked': 'A conta de superadministrador não pode ser editada nem excluída aqui.',
  'users.configuration': 'Configuração do usuário',
  'users.newPassword': 'Nova senha',
  'users.retypePassword': 'Digite a senha novamente',
  'users.globalPermissions': 'Permissões globais',
  'users.serverAccess': 'Acesso deste usuário ao servidor',
  'users.currentAccess': 'Acesso atual',
  'users.noAccess': 'Sem acesso',
  'users.custom': 'Personalizado',
  'users.quickPresets': 'Predefinições rápidas',
  'users.general': 'Geral',
  'users.fileManager': 'Gerenciador de arquivos',
  'users.scheduledTasks': 'Tarefas agendadas',
  'users.saveChanges': 'Salvar alterações',
  'users.retry': 'Tentar novamente',
  'users.deleteTitle': 'Excluir usuário',
  'users.deleteMessage': 'Excluir “{username}” agora? Essa ação remove permanentemente a conta e não pode ser desfeita.',
  'users.deleteMessageGeneric': 'Essa ação remove permanentemente a conta e não pode ser desfeita.',
  'users.required': 'Nome de usuário e senha são obrigatórios.',
  'users.usernameRequired': 'O nome de usuário é obrigatório.',
  'users.passwordLength': 'A senha deve ter pelo menos 8 caracteres.',
  'users.passwordMismatch': 'A confirmação da senha não corresponde.',
  'users.confirmNewPassword': 'Confirme a nova senha.',
  'users.loadError': 'Não foi possível carregar os usuários.',
  'users.permissionsLoadError': 'Não foi possível carregar as permissões do servidor.',
  'users.createError': 'Não foi possível criar o usuário.',
  'users.saveError': 'Não foi possível salvar as alterações do usuário.',
  'users.deleteError': 'Não foi possível excluir o usuário.',
  'users.created': 'Usuário {username} criado com sucesso.',
  'users.saved': 'Alterações do usuário salvas com sucesso.',
  'users.deleted': 'Usuário {username} excluído.',
  'users.serverAccessDescription': 'Configure um servidor por vez, com status de acesso e ações bem definidos',
  'users.selectServer': 'Selecionar servidor',
  'users.setPermissions': 'Definir permissões para {server}',
  'preset.viewer': 'Visualizador',
  'preset.operator': 'Operador',
  'preset.full': 'Acesso completo',
  'permission.users.manage': 'Administrar usuários',
  'permission.server.install': 'Instalar servidores',
  'permission.server.power': 'Iniciar, parar e reiniciar',
  'permission.container.logs.read': 'Ler logs do servidor',
  'permission.server.command.send': 'Acessar o console do servidor',
  'permission.server.edit': 'Editar propriedades do contêiner',
  'permission.server.env': 'Administrar variáveis de ambiente',
  'permission.container.terminal': 'Acessar o terminal do contêiner',
  'permission.server.delete': 'Excluir servidor',
  'permission.scheduledtasks.read': 'Ver tarefas agendadas',
  'permission.scheduledtasks.write': 'Administrar tarefas agendadas',
  'permission.fs.read': 'Ler arquivos',
  'permission.fs.write': 'Gravar arquivos',
  'permission.backups.read': 'Ver backups',
  'permission.backups.create': 'Criar backups',
  'permission.backups.restore': 'Restaurar backups',
  'permission.backups.download': 'Baixar backups',
  'permission.backups.delete': 'Excluir backups',
  'permission.backups.rename': 'Renomear backups',
  'permission.backups.settings.write': 'Editar configurações de backup',
  'permission.server.wipe.soft': 'Limpeza parcial',
  'permission.server.wipe.hard': 'Limpeza completa',
  'permission.palworld.settings.read': 'Ver configuração do jogo',
  'permission.palworld.settings.write': 'Editar configuração do jogo',
  'permission.cs2.frameworks.write': 'Administrar frameworks',
  'permission.minecraft.settings.read': 'Ver configuração do jogo',
  'permission.minecraft.settings.write': 'Editar configuração do jogo',
  'permission.minecraft.operators.read': 'Ver operadores',
  'permission.minecraft.operators.write': 'Administrar operadores',
  'permission.minecraft.whitelist.read': 'Ver lista de permissões',
  'permission.minecraft.whitelist.write': 'Administrar lista de permissões',
  'permission.minecraft.bans.read': 'Ver banimentos de jogadores',
  'permission.minecraft.bans.write': 'Administrar banimentos de jogadores',
  'permission.minecraft.ip-bans.read': 'Ver banimentos de IP',
  'permission.minecraft.ip-bans.write': 'Administrar banimentos de IP',
  'permission.minecraft.addons.read': 'Ver mods e plugins',
  'permission.minecraft.addons.write': 'Administrar mods e plugins',
  'permission.hytale.settings.read': 'Ver configuração do jogo',
  'permission.hytale.settings.write': 'Editar configuração do jogo',
  'permission.hytale.mods.read': 'Ver mods',
  'permission.hytale.mods.write': 'Administrar mods',
  'permission.project-zomboid.settings.read': 'Ver configuração do jogo',
  'permission.project-zomboid.settings.write': 'Editar configuração do jogo',
  'permission.project-zomboid.mods.read': 'Ver mods',
  'permission.project-zomboid.mods.write': 'Administrar mods',
  'resources.title': 'Recursos e tutoriais',
  'resources.description': 'Aprenda a administrar seus servidores de jogos com eficiência',
  'resources.search': 'Buscar recursos',
  'resources.searchPlaceholder': 'Busque por título, descrição ou chave do jogo…',
  'resources.filter': 'Filtrar por categoria',
  'resources.all': 'Todas',
  'resources.showingOne': 'Exibindo 1 recurso',
  'resources.showingMany': 'Exibindo {count} recursos',
  'resources.loading': 'Carregando recursos…',
  'resources.loadErrorTitle': 'Não foi possível carregar os recursos',
  'resources.loadError': 'Não foi possível carregar os recursos agora.',
  'resources.showLess': 'Mostrar menos',
  'resources.showMore': 'Ver mais recursos ({count} a mais)',
  'resources.none': 'Nenhum recurso encontrado',
  'resources.noneHint': 'Tente ajustar a busca ou o filtro',
};

function resolveInitialLocale(): AppLocale {
  const saved = localStorage.getItem(STORAGE_KEY);
  if (saved === 'en' || saved === 'pt-BR') return saved;
  return navigator.language.toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
}

type LanguageContextValue = {
  locale: AppLocale;
  setLocale: (locale: AppLocale) => void;
  t: (key: string, fallback?: string, values?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<AppLocale>(resolveInitialLocale);

  const setLocale = (next: AppLocale) => {
    localStorage.setItem(STORAGE_KEY, next);
    setLocaleState(next);
  };

  useEffect(() => {
    document.documentElement.lang = locale === 'pt-BR' ? 'pt-BR' : 'en';
    return watchLegacyInterface(locale === 'pt-BR');
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale,
    t: (key, fallback = key, values = {}) => {
      let translated = locale === 'pt-BR' ? (ptBR[key] ?? fallback) : fallback;
      for (const [name, replacement] of Object.entries(values)) {
        translated = translated.split(`{${name}}`).join(String(replacement));
      }
      return translated;
    },
  }), [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
